### ISSUE TITLE
Add woff2 format

### ISSUE THREAD

**Issue by ucodi** [atisawd/boxicons#10]
WOFF2 uses custom preprocessing and compression algorithms to deliver ~30% file-size reduction over other formats. For more information, see [the WOFF 2.0 evaluation report](https://www.w3.org/TR/WOFF20ER/)

**Comment by atisawd** [comment]
I will look into it, will probably add it this weekend

**Comment by atisawd** [comment]
woff2 font has been added thanks for raising this issue
