### ISSUE TITLE
Icons have changed

### ISSUE THREAD

**Issue by Percyvalmg** [atisawd/boxicons#108]
My website https://www.yelah.co.za/ and all my icons are reference other icons instead of their original icons.

My instagram icon is now the linkedin icon
My twitter icon is now the wikipedia icon

I am using your cdn

**Comment by thenilaymodi** [comment]
Yes, I had this same issue!

**Comment by atisawd** [comment]
please use the version number when using the icons 
https://unpkg.com/boxicons@2.0.6/css/boxicons.min.css
