### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by jesper9610** [atisawd/boxicons#13]
For some reason all the SVG icons are blank in Edge. Regularly font icons works fine. From what i can find Edge supports SVG. So i'm not sure what's going on. 

I'm using the icons on a locally run projects.

**Comment by jesper9610** [comment]
My bad someone please delete this.

**Comment by atisawd** [comment]
Thanks for confirming its not issue

**Comment by philbeauchamp** [comment]
> My bad someone please delete this.

I know this is closed but am having the same issue and cannot figure it out.  Works perfectly on Chrome.  rexDesigndk, what did you do to fix it?

**Comment by rexdesigndk** [comment]
> > My bad someone please delete this.
> 
> I know this is closed but am having the same issue and cannot figure it out. Works perfectly on Chrome. rexDesigndk, what did you do to fix it?

This is awkward... I actually can't remember. I ended up switching over to ionicons. Because of their better license
