### ISSUE TITLE
Lates set of SVG images are broken - missing viewBox attribute

### ISSUE THREAD

**Issue by purtuga** [atisawd/boxicons#16]
Looks like the last update ( [v1.8.0](https://github.com/atisawd/boxicons/commit/7de0e2003a6db2f96c5832e36835e11224fb282b) ) broke the use of SVG images - the `viewBox="0 0 24 24"` was removed from the `<svg>` tag, which mean we are not able to apply different sizes to them - they are fixed at 24x24.  

You should be able to see this issue if you use the web component `<box-icon>`.

**Comment by atisawd** [comment]
i will correct it in the update , thanks for this

**Comment by atisawd** [comment]
Corrected in 1.8.1, Thanks again
