### ISSUE TITLE
Icons have shrunk at version 2.0.8

### ISSUE THREAD

**Issue by mikepianka** [atisawd/boxicons#187]
I noticed in my web pages that use the unpkg latest CDN that the icons have shrunk with the 2.0.8 update. Was that intentional?

2.0.7
![image](https://user-images.githubusercontent.com/47948499/126545696-e7f7ddc6-d2a1-42b9-8f9c-04ea77dfe7b1.png)

2.0.8 / latest
![image](https://user-images.githubusercontent.com/47948499/126545990-b46ed5c8-59e1-40f8-9993-49612dba73d0.png)

**Comment by atisawd** [comment]
i will look into this and wll be resolved soon

**Comment by atisawd** [comment]
please confirm if this has been resolved in 2.0.9

**Comment by mikepianka** [comment]
Thanks for the fix, I will give it a try tomorrow to confirm.

**Comment by mikepianka** [comment]
This is fixed with the new v2.0.9 release. 👏 Thank you for the quick response. I'll close this issue.
