### ISSUE TITLE
Invoice and Leads Icons

### ISSUE THREAD

**Issue by IYASSDEV** [atisawd/boxicons#20]
Hello,

It would be cool if you can make an Invoice, Leads icon

Invoice example: 
![image](https://user-images.githubusercontent.com/44617192/48874949-45960f00-edf6-11e8-91a3-0a0e91e20fda.png)
Leads example: 
![image](https://user-images.githubusercontent.com/44617192/48874969-6e1e0900-edf6-11e8-98a4-9812e9a99b60.png)

Thank you for your hard work 👍

**Comment by atisawd** [comment]
Cool will try to add these in the next update +1

**Comment by IYASSDEV** [comment]
Any news?
