### ISSUE TITLE
please add a icon for PDF

### ISSUE THREAD

**Issue by NewLuckyLuke** [atisawd/boxicons#23]
It would be great to have a icon for a document in PDF format.
<img width="277" alt="filemaker pro advancedscrnsnpz247" src="https://user-images.githubusercontent.com/32767014/51840363-280c8680-230c-11e9-90d0-550c647e6a9e.png">
Many thnx for the wonderful icons

**Comment by atisawd** [comment]
Will do In the next update

**Comment by NewLuckyLuke** [comment]
Great! Many thanks.

Luc

On 28 Jan 2019, at 17:08, Atisa <notifications@github.com<mailto:notifications@github.com>> wrote:


Will do In the next update

**Comment by atisawd** [comment]
added the pdf icon

**Comment by NewLuckyLuke** [comment]
thnx! 
Keep up the fantastic work! It's really appreciated!
