### ISSUE TITLE
Icons for vertical expansion/collapse

### ISSUE THREAD

**Issue by illright** [atisawd/boxicons#237]
I'm looking for icons to use in an accordion for vertical expansion/collapse, but the `expand` and `collapse` icons in Boxicons convey expansion in all directions. Ideally, I'd like to see icons for vertical expansion/collapse:
![image](https://user-images.githubusercontent.com/15035286/138855652-aadd6434-0e48-47cd-b25e-10890a3bd28c.png)

Alternatively, I could use `expand-alt` if it had a `collapse-alt` to pair with it.

**Comment by atisawd** [comment]
added in 2.1.0
