### ISSUE TITLE
Call Regular has been removed

### ISSUE THREAD

**Issue by fayazara** [atisawd/boxicons#24]
Hello team,

I was using this icon `<i class="bx bx-phone-call"></i>` in v1.8.1 I see it is missing from the latest version 1.9.1, can you please clarify why it has been removed or when it will be added back?

**Comment by Wylkon** [comment]
The `book-bookmark` also has been removed. :/ Should I create another issue?

**Comment by atisawd** [comment]
I will add them again in future updates will be done in March though

**Comment by atisawd** [comment]
added them back
