### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danuapratama** [atisawd/boxicons#251]
The icon changes when it's opened on the phone with chrome or edge, but there's no problem when it's on the desktop, even though the code I'm using is still the same. Is this a bug?

**Comment by atisawd** [comment]
i am not sure , its working on my side on the phone and tab

**Comment by danuapratama** [comment]
> i am not sure , its working on my side on the phone and tab

Really? Did this happen to me myself? Because it just happened today, previously there was no problem with the icon. For example, you can visit my portfolio https://danuapratama.github.io and try to see the icon changes that occur, then try to compare it on the mobile and desktop versions. Thank you in advance for the response

**Comment by danuapratama** [comment]
> i can see the icons on the bottom and the social media section on the mobile version too , please try deleting the cache and use a specific version while using the font if possible
> 
> its probably because of the update today , you need to use specific versions to avoid this , not the latest

Yes thank you. This solution worked for me. Have a nice day

**Comment by SoleeL** [comment]
I have the same problem.

Switch to the stylesheet of unpkg and it is fixed.

`<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">`

Check my cache and it seems that the content of each icon is interchanged.

<img src="https://user-images.githubusercontent.com/26660417/144471029-dbffb977-4ce6-4270-a112-7c639646ed06.png" width=50% height=50%>

**Comment by danuapratama** [comment]
> I have the same problem.
> 
> Switch to the stylesheet of unpkg and it is fixed.
> 
> `<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">`
> 
> Check my cache and it seems that the content of each icon is interchanged.
> 
> <img src="https://user-images.githubusercontent.com/26660417/144471029-dbffb977-4ce6-4270-a112-7c639646ed06.png" width=50% height=50%>

Yes, thank you. I will try it

**Comment by atisawd** [comment]
please stop using <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

and use <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.0/css/boxicons.min.css">

**Comment by atisawd** [comment]
please stop using `<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">`
and use specific versions `<link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.0/css/boxicons.min.css">`

**Comment by atisawd** [comment]
I dont know how to keep the unicode while creating font , if anyone can help it would be helpful

**Comment by atisawd** [comment]
found  a method to keep the unicode the same , it wont be a problem in future updates
