### ISSUE TITLE
404 for boxicons homepage

### ISSUE THREAD

**Issue by AnilSeervi** [atisawd/boxicons#253]
https://boxicons.com
![boxicons com_(iPhone 5_SE)](https://user-images.githubusercontent.com/61609033/145818827-185cd4d3-7f3a-4419-bdeb-14300f8da896.png)

**Comment by atisawd** [comment]
sorry for the inconvenience , it should be back up again

**Comment by AnilSeervi** [comment]
> sorry for the inconvenience , it should be back up again

It is. Thanks!
