### ISSUE TITLE
Failed to load icon: detail

### ISSUE THREAD

**Issue by ThomasMaitret** [atisawd/boxicons#27]
Hello,
I have the following error when trying to use the detail solid icon:

Failed to load icon: detail
Error: 404 Cannot find "/svg/regular/bx-detail.svg" in boxicons@1.9.3

(The icon displays correctly though)

**Comment by atisawd** [comment]
It was removed in the recent versions, I will try to restore it in the coming version, in a week max

**Comment by atisawd** [comment]
Sorry for the delay , it has been added

**Comment by iamnirav** [comment]
Hi, I'm having the same issue for the solid `dashboard`. The icon displays correctly but the error displays in the console.

**Comment by chaitanya415** [comment]
As mentioned by @iamnirav, below is the error in console for "dashboard". however the icon displays correctly.

Failed to load icon: dashboard
Error: 404 Cannot find "/svg/regular/bx-dashboard.svg" in boxicons@2.0.5

**Comment by atisawd** [comment]
I  will look into this today thanks for the heads up

**Comment by mojdeeeeeh** [comment]
Hi, I installed the boxicons package, I use it well for my project, but I have an error in the console for icons with **solid type.**
_Failed to load icon: bank
Error: 404 Cannot find "/svg/regular/bx-bank.svg" in boxicons@2.1.2_

Also, the styles that you put, such as the size, were not applied.

**Comment by ekyza** [comment]
Hi, I'm having the same issue for the logo instagram. The icon displays correctly but the error displays in the console.

**Comment by jb0o** [comment]
Same here;
```
<box-icon name='facebook' type='logo'></box-icon>
```

Renders the following in console;

```
Failed to load icon: facebook
Error: 404 Cannot find "/svg/regular/bx-facebook.svg" in boxicons@2.1.4
```

**Comment by Albinzr** [comment]
boxxicons.js:1 Failed to load icon: file-doc

**Comment by David-Encinas** [comment]
bump

**Comment by gcristianber** [comment]
Is this already fixed? I currently experiencing this issue, how can I fix this?
