### ISSUE TITLE
Optimize SVG files

### ISSUE THREAD

**Issue by stidges** [atisawd/boxicons#3]
First of all, thanks for these icons! I was wondering if it is possible to add optimized versions of the SVG icons - currently they contain a lot of things that can be removed, like Illustrator comments and doctype. Using a tool like [svgo](https://github.com/svg/svgo) this can easily be achieved. Would be happy to make a PR too!

**Comment by atisawd** [comment]
thanks for the suggestion , i was very excited to release this , looks like i forgot to look at the small details. i will look into svgo , does it remove the unnecessary stuff?
