### ISSUE TITLE
Svg icon no viewbox

### ISSUE THREAD

**Issue by rowdy-dowdy** [atisawd/boxicons#312]
I can't enlarge the icon (copying the svg and using the web component doesn't work either)
![image](https://user-images.githubusercontent.com/33823245/157604652-152e5cdd-165c-4abc-858b-73f5c5445db5.png)

**Comment by atisawd** [comment]
i will fix it in the new version , sorry for the inconvenience

**Comment by kerryj89** [comment]
> i will fix it in the new version , sorry for the inconvenience

I downgraded to 2.1.1 for now.  Thank you for providing us high quality icons for free!
