### ISSUE TITLE
up-arrow-circle === down-arrow-circle (solid)

### ISSUE THREAD

**Issue by chiangs** [atisawd/boxicons#34]
up-arrow-circle and down-arrow-circle both result in down-arrow-circle (solid)
- documentation
- implementation via web-components

Expected behavior is that up-arrow-circle has an arrow pointing up.

![image](https://user-images.githubusercontent.com/10984593/57831454-765b6d80-77b5-11e9-8727-0c4f9177b730.png)

**Comment by atisawd** [comment]
Looks like I messed up with the up arrow circle, for now you Could use the 'flip' option to flip the arrow vertically

**Comment by atisawd** [comment]
It has been corrected in the 2.0.3 update :)
