### ISSUE TITLE
adobe XD plugin

### ISSUE THREAD

**Issue by b3u** [atisawd/boxicons#37]
I've been working on a plugin for adobe xd which allows users to choose an icon from the boxicons library. I know that the library license is MIT, but I thought it would be polite to inform you that it might go live. Also, I was wondering whether when it is finished, if it can become the "official" boxicons xd plugin. That would allow me to use the boxicons logo and the boxicons homepage.

The working repo is [here](https://github.com/b3u/boxicons-xd)

Cheers!

**Comment by atisawd** [comment]
yea sure go ahead , but please dont resell it , and give credits if possible
