### ISSUE TITLE
IMDB Icon Request

### ISSUE THREAD

**Issue by Shrinks99** [atisawd/boxicons#39]
This seems like an excellent tool!  The only thing preventing me from using it is the lack of an IMDB icon, having that would be super excellent.

Also some sort of submission template & guidelines would be neat, that way others can contribute with (hopefully) a minimal amount of "this is wrong" for new icons.  Just a thought!

**Comment by atisawd** [comment]
Will add it in the new update , end of this month hopefully. I will work on the new icon submission stuff too :)

**Comment by atisawd** [comment]
It has been added in the 2.0.3 update :)
