### ISSUE TITLE
error: failed to load icon quote-alt-left

### ISSUE THREAD

**Issue by b3u** [atisawd/boxicons#45]
When I use the icon component in react, and I try to use
```jsx
<Box-icon name="quote-alt-left" type="solid" />
```
I get the following error (icon displays correctly, though)
```
Failed to load icon: quote-alt-left
Error: 404 Cannot find '/svg/regular/bx-quote-alt-left.svg' in boxicons@2.0.2
```
I took a peek in the js, and I couldn't find anything amiss. Thanks!

**Comment by Nikodemsky** [comment]
Same issue here.

**Comment by atisawd** [comment]
I don't know its working when I try it on code pen [Here](https://codepen.io/atisawd/pen/WNeGQMy)

**Comment by Nikodemsky** [comment]
I'm not saying it's not working - it simply gives 404 errors in console for some of the icons(in my case pinterest, instagram and twitter, solid type).

**Comment by atisawd** [comment]
Tbh I have no clue then. Is it because of the cdn server being down?

**Comment by b3u** [comment]
Huh. Working for me as well now. Feel free to close.
