### ISSUE TITLE
Currency icon Request

### ISSUE THREAD

**Issue by saha6984** [atisawd/boxicons#46]
I like the styling of BOX ICON just loving each and every icon thanks to the team Box Icon, would suggest having Currency icon:

bitcoin, dollar-sign, euro-sign, lira-sign, pound-sign, ruble-sign, rupee-sign, shekel-sign, won-sign, yen-sign 

Thanks
Prameshwar

**Comment by atisawd** [comment]
They have been added in the 2.0.3 update :)
