### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by lifeiscontent** [atisawd/boxicons#48]
Hi there, I'm building a library, and I'm wondering if I can use boxicons in my library, if so, what are the terms here?

**Comment by rexdesigndk** [comment]
From their website

> Boxicons is an open source project , you can use them in your commercial projects too.
The icons (.svg) files are free to download and are licensed under CC 4.0 . By downloading it is assumed that you agree with the terms mentioned in CC 4.0.
The fonts files are licensed under SIL OFL 1.1
Attribution is not required but is appreciated
Other files which are not fonts or icons are licensed under the MIT License

**Comment by b3u** [comment]
@lifeiscontent Do you want to close this issue, since it seems to be resolved?
