### ISSUE TITLE
Icon request: refresh

### ISSUE THREAD

**Issue by zadam** [atisawd/boxicons#58]
![image](https://user-images.githubusercontent.com/617641/68070335-515fb480-fd6d-11e9-8871-35d463544742.png)

Thanks for great icon pack!

**Comment by b3u** [comment]
@zadam does `bx-revision` work for you? ![bx-revision](https://boxicons.com/static/img/svg/regular/bx-revision.svg)

Also, you probably should let him know where you got the icon from, or if you designed it yourself.

**Comment by zadam** [comment]
Revision could work, but it's not the exact same meaning IMHO.

For now I'm using `bx-recycle`:

![grafik](https://user-images.githubusercontent.com/617641/69318577-bbb59780-0c3d-11ea-89fc-177d06adb4c4.png)

**Comment by atisawd** [comment]
will add in the new update

**Comment by atisawd** [comment]
added in 2.0.5
