### ISSUE TITLE
Icon request: shield with X

### ISSUE THREAD

**Issue by zadam** [atisawd/boxicons#60]
Hello, there's an check-shield icon which can be used for e.g. marking that something is secured. For expressing the opposite - i.e. that something is not secured, it would be great to have a shield with X sign instead of check symbol or possibly shield with strike through. 

Something like this: 
![image](https://user-images.githubusercontent.com/617641/68082066-2d0ce200-fe18-11e9-88ee-1720d1e96c0c.png)

**Comment by atisawd** [comment]
will add in the new update

**Comment by atisawd** [comment]
added in 2.0.5
