### ISSUE TITLE
Icon request: incomplete task

### ISSUE THREAD

**Issue by zadam** [atisawd/boxicons#65]
There's a nice task icon:

![image](https://user-images.githubusercontent.com/617641/69754381-0e1f1880-1156-11ea-9c43-e57564391e40.png)

But the problem is that the check suggests that it has been completed. It would be nice to provide a variant without the check which would mean "not completed task".

**Comment by atisawd** [comment]
will add in the new update

**Comment by atisawd** [comment]
added in 2.0.5
