### ISSUE TITLE
Change color on hover animation

### ISSUE THREAD

**Issue by Shrinks99** [atisawd/boxicons#66]
Adding a color change state on hover animation would be super helpful for things like the social icons.

**Comment by atisawd** [comment]
you can do it using css with a few code , or am i interpreting it wrong? can you share an example

**Comment by Shrinks99** [comment]
I'm using the web component and when I give it a class and set the `color` value of the class on `:hover` in CSS it doesn't seem to work.  Everything works as expected with the regular CSS version

[Example available here!](https://codepen.io/shrinks99/pen/pozxLQz?editors=1100)

**Comment by justin22** [comment]
@Shrinks99  to change color on hover,
in the case of`<box-icon>`, try`fill: 'your-color';` 
and for `<i>`, try`color: 'your-color';`

**Comment by Shrinks99** [comment]
@justin22 Have since switched to the non-javascript version but ugh, now I feel like a moron, of course this works because they're SVGs >_<

Going to close this because this is not really a bug, this should probably be added to the readme or somewhere at some point.
