### ISSUE TITLE
Icon Request: Linux

### ISSUE THREAD

**Issue by Shrinks99** [atisawd/boxicons#75]
A [tux](https://en.wikipedia.org/wiki/Tux_(mascot)) icon would be super handy for software developers who want to use multiple OS icons.  Including a handful of distro icons (Ubuntu, Arch, Debian, etc) wouldn't be a bad idea either.

**Comment by Aleksandar-Mitic** [comment]
Hope this will be added soon...

**Comment by Shrinks99** [comment]
I'm happy to do the icon and submit it as an SVG but I have no idea how to make the rest of everything work because there's no documentation :(

**Comment by atisawd** [comment]
it will be added in the next update , i have had some problems during the covid , finally got some time for this

**Comment by FrancescoBorzi** [comment]
hello, having Linux icons would be much appreciated!

thanks

**Comment by Shrinks99** [comment]
Looks like this can be closed with the addition of `tux`, thank you @atisawd!!
