### ISSUE TITLE
Is there is any way to copy SVG code of the icon directly from the website?

### ISSUE THREAD

**Issue by iamsahilvhora** [atisawd/boxicons#76]
Something like this website: [https://heroicons.dev/](https://heroicons.dev/)

You can click on the icon and it will copy the SVG code to the clipboard.

**Comment by Shrinks99** [comment]
This issue hasn't been updated yet but there's a download SVG button now!

**Comment by iamsahilvhora** [comment]
Any update on this one? 
I really want to use Boxicons on my web projects but it is really time-consuming to download the SVG icon every time and then copy its SVG code.

**Comment by atisawd** [comment]
I will try to add that feature in the website , is there some js package that you know of , that can help me achieve that?

**Comment by atisawd** [comment]
Its been added , do check it out

**Comment by iamsahilvhora** [comment]
@atisawd It's perfect! Thank you so much. This is going to be a great time-saver.
