### ISSUE TITLE
Eye Icon

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [atisawd/boxicons#805]
Something like that:
![WhatsApp Image 2024-05-20 at 20 49 41_9d903ef8](https://github.com/atisawd/boxicons/assets/77451351/2845e3a5-2c22-4faf-936e-49da7ba6f679)

**Comment by hosseingh16** [comment]
Yeah that's missing

**Comment by hosseingh16** [comment]
I found it, search "show" and "Hide" icons
